<a href="https://colab.research.google.com/github/suryogumilar/Tensorflow_timeseries/blob/main/C4_W3_Lab_2_LSTM_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using a multi-layer LSTM for forecasting

without `tf.function`, `tf.function(reduce_retracing=True)` and try using multivariate input


In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import datetime
from dateutil.relativedelta import relativedelta
# for timezone()
import pytz
import math
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import plotly.graph_objects as go
from IPython.display import clear_output
import random
import os
from sklearn.preprocessing import MinMaxScaler

## Function

### Plot functions

In [2]:
def plot_series(time, series, format="-", start=0, end=None):
    """
    Visualizes time series data

    Args:
      time (array of int) - contains the time steps
      series (array of int) - contains the measurements for each time step
      format - line style when plotting the graph
      label - tag for the line
      start - first time step to plot
      end - last time step to plot
    """

    # Setup dimensions of the graph figure
    plt.figure(figsize=(10, 6))
    
    if type(series) is tuple:

      for series_num in series:
        # Plot the time series data
        plt.plot(time[start:end], series_num[start:end], format)

    else:
      # Plot the time series data
      plt.plot(time[start:end], series[start:end], format)

    # Label the x-axis
    plt.xlabel("Time")

    # Label the y-axis
    plt.ylabel("Value")

    # Overlay a grid on the graph
    plt.grid(True)

    # Draw the graph on screen
    plt.show()

In [3]:
def plot_series_plotly(time, series, series_name=None, 
                       figure_title='', showlegend=False, 
                       start=0, end=None,
                       xaxis_title="Time",
                       yaxis_title="Value"):
    """
    Visualizes time series data but using plotly for interactive graph

    Args:
      time (array of int) - contains the time steps
      series (array of int) - contains the measurements for each time step
      series_name (array of string) - contains correlative name of each series
      format - line style when plotting the graph
      label - tag for the line
      start - first time step to plot
      end - last time step to plot
    """
    fig = go.Figure()
    # Setup dimensions of the graph figure
    
    if type(series) is tuple:
      ii = 0
      for series_num in series:
        # Plot the time series data
        fig.add_trace(go.Scatter(x=time[start:end],
                                 y=series_num[start:end], mode='lines',
                                 name=series_name[ii]))  
        ii = ii+1
    else:
      # Plot the time series data
      fig.add_trace(go.Scatter(x=time[start:end],
                                 y=series[start:end], mode='lines'))

    fig.update_layout(title=figure_title, xaxis_title=xaxis_title, 
                      yaxis_title=yaxis_title,
                      autosize=False,
                      width=600,
                      height=600,
                      margin=dict(
                        l=50,
                        r=50,
                        b=100,
                        t=100,
                        pad=4
                        ), paper_bgcolor="LightSteelBlue"
                        , showlegend=showlegend
                      )
    fig.show()

In [4]:
def plot_candlesticks(df, figure_title='', showlegend=False):
  fig = go.Figure(data= [go.Candlestick(x=df['Date'],
                             open=df['Open'],
                             high=df['High'],
                             low=df['Low'],
                             close=df['Close']
                             )])
  fig.update_layout(title=figure_title, xaxis_title="Time", yaxis_title="Value",
                    autosize=False,
                    width=600,
                    height=600,
                    margin=dict(
                        l=50,
                        r=50,
                        b=100,
                        t=100,
                        pad=4
                    ),
                    paper_bgcolor="LightSteelBlue", showlegend=showlegend
                  )
  fig.show()

In [5]:
def plot_loss_inlog(history, epoch_value, lrs_value=1e-8, 
                    x_boundary1=1e-8, x_boundary2=1e-3,
                    y_boundary1=0, y_boundary2=50):
  """
  plot loss value after training in logaritmic scale

  Parameters:
    lrs_value: learning rate value that passed to LearningRateScheduler function
  """
  # Define the learning rate array
  lrs = lrs_value * (10 ** (np.arange(epoch_value) / 20))

  # Set the figure size
  plt.figure(figsize=(10, 6))

  # Set the grid
  plt.grid(True)

  # Plot the loss in log scale
  plt.semilogx(lrs, history.history["loss"])

  # Increase the tickmarks size
  plt.tick_params('both', length=10, width=1, which='both')

  # Set the plot boundaries
  plt.axis([x_boundary1, x_boundary2, 
            y_boundary1, y_boundary2])

In [6]:
def plot_loss_inlog_plotly(history, epoch_value, lrs_value=1e-8,
                           figure_title='Loss value', showlegend=False):
  """
  plot loss value after training in logaritmic scale

  Parameters:
    lrs_value: learning rate value that passed to LearningRateScheduler function
  """
  # Define the learning rate array
  lrs = lrs_value * (10 ** (np.arange(epoch_value) / 20))
  fig = go.Figure()
  fig.add_trace(go.Scatter(x=lrs,
                           y=history.history['loss'], mode='lines'))
  fig.update_xaxes(title_text="learning rate", type="log")
  
  fig.update_layout(title=figure_title, xaxis_title="Time", yaxis_title="Value",
                      autosize=False,
                      width=600,
                      height=600,
                      margin=dict(
                        l=50,
                        r=50,
                        b=100,
                        t=100,
                        pad=4
                        ), paper_bgcolor="LightSteelBlue"
                        , showlegend=showlegend
                      )
  fig.show()

In [7]:
def plot_prediction_graph(model, df, training_ds_rows,
                          window_size, 
                          normalizer_univar, denormalizer_univar,
                          variable_names='Close'):
  # Initialize a list
  forecast = []
  dataset_to_forecast = df[variable_names].iloc[training_ds_rows-window_size:]
  dateset_to_forecast_normalized = normalizer_univar(dataset_to_forecast)
  for time in range(dateset_to_forecast_normalized.shape[0] - window_size):
    the_prediction = model.predict(
        np.expand_dims(dateset_to_forecast_normalized[time:time + window_size], 
                      axis=0), 
        verbose=0)
    the_prediction_denorm = denormalizer_univar(the_prediction)
    forecast.append(the_prediction_denorm)
    
  # Convert to a numpy array and drop single dimensional axes
  results = np.array(forecast).squeeze()

  # Overlay the results with the validation set
  test_set = tf.convert_to_tensor(df[training_ds_rows:][variable_names])
  plot_series(df_test['Date'], (test_set, results) )
  return (test_set, results)

In [8]:
def plot_prediction_graph_plotly(model, df, training_ds_rows, 
                          window_size, normalizer_univar, denormalizer_univar,
                          scaler=None,
                          variable_names='Close',
                          series_name=['test dataset', 'predicted value']):
  # Initialize a list
  forecast = []
  dataset_to_forecast = df[variable_names].iloc[training_ds_rows-window_size:]
  if(normalizer_univar is not None):
    dateset_to_forecast_normalized = normalizer_univar(dataset_to_forecast)
  else:
    dateset_to_forecast_normalized = scaler.transform(dataset_to_forecast.values)
    print('dateset_to_forecast shape:', dateset_to_forecast_normalized.shape)
    print('expanded dateset_to_forecast shape:',
          np.expand_dims(dateset_to_forecast_normalized[0:window_size], 
                      axis=0).shape)
  for time in range(dateset_to_forecast_normalized.shape[0] - window_size):
    the_prediction = model.predict(
        np.expand_dims(dateset_to_forecast_normalized[time:time + window_size], 
                      axis=0), 
        verbose=0)
    if(denormalizer_univar is not None):
      the_prediction_denorm = denormalizer_univar(the_prediction)
    else:
      the_prediction_denorm = scaler.inverse_transform(the_prediction)
    forecast.append(the_prediction_denorm)
    
  # Convert to a numpy array and drop single dimensional axes
  print('forecast shape', np.array(forecast).shape)
  results = np.array(forecast).squeeze()
  print('forecast squeezed shape', results.shape)
  # Overlay the results with the validation set
  test_set = tf.convert_to_tensor(df[training_ds_rows:][variable_names])

  plot_series_plotly(df_test['Date'], (test_set[:,-1], results[:,-1]), 
                     series_name=series_name )
  return (test_set, results)

### function data retrieval

In [9]:
def getStockData(history_span:int, the_ticker:str):
  """
  Getting stock data from Yahoo Finance API

  Args:
    history_span (int) how much backdate data to be collected
    the_ticker (string) ticker name on yahoo finance API
  Returns:
    Pandas dataframe (pd.DataFrame) containing stock data    
  """
  THE_URL = ('https://query1.finance.yahoo.com/v7/finance/'+
           'download/{ticker}?period1={period1}&period2={period2}&interval=1d&events=history&includeAdjustedClose=true')
  tdy = datetime.datetime.now(tz=pytz.timezone('Asia/Jakarta'))

  p2 = math.ceil(tdy.timestamp())
  p1 = math.floor((tdy - relativedelta(years=history_span)).timestamp())
  yf_url = THE_URL.format(ticker=the_ticker,period1=p1, period2=p2)
  df = pd.read_csv(yf_url)
  df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')
  return df

### Make windowed data for time series forecasting


In [10]:
def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
    """Generates dataset windows

    Args:
      series (array of float) - contains the values of the time series
      window_size (int) - the number of time steps to include in the feature
      batch_size (int) - the batch size
      shuffle_buffer(int) - buffer size to use for the shuffle method

    Returns:
      dataset (TF Dataset) - TF Dataset containing time windows
    """
  
    # Generate a TF Dataset from the series values
    dataset = tf.data.Dataset.from_tensor_slices(series)
    
    # Window the data but only take those with the specified size
    dataset = dataset.window(window_size + 1, shift=1, drop_remainder=True)
    
    # Flatten the windows by putting its elements in a single batch
    dataset = dataset.flat_map(lambda window: window.batch(window_size + 1))

    # Create tuples with features and labels 
    dataset = dataset.map(lambda window: (window[:-1], window[-1]))

    # Shuffle the windows
    dataset = dataset.shuffle(shuffle_buffer)
    
    # Create batches of windows
    dataset = dataset.batch(batch_size).prefetch(1)
    
    return dataset

## Tensorflow function

In [11]:
def set_seed(seed: int = 42) -> None:
  random.seed(seed)
  np.random.seed(seed)
  tf.random.set_seed(seed)
  tf.experimental.numpy.random.seed(seed)
  #tf.keras.utils.set_random_seed(seed)
  #tf.config.experimental.enable_op_determinism()
  try:
    tf.set_random_seed(seed)
  except AttributeError as ae:
    print('INFO: tf.set_random_seed is deprecated in tf version ', tf.__version__, ' ',ae )
  
  # When running on the CuDNN backend, two further options must be set
  os.environ['TF_CUDNN_DETERMINISTIC'] = '1'
  os.environ['TF_DETERMINISTIC_OPS'] = '1'
  # Set a fixed value for the hash seed
  os.environ["PYTHONHASHSEED"] = str(seed)
  print(f"Random seed set as {seed}")

## get data

In [12]:
# stock_name = str(input("Stock tick:"))
# hist_data = int(input("historical data (year):"))

stock_name = 'TLKM.JK'
hist_data = 3
     

In [13]:
df = getStockData(hist_data, stock_name)

In [16]:
plot_candlesticks(df, figure_title='stock candlestick graph', showlegend=False)

## Split the Dataset

In [17]:
split_ratio = 0.8
rows_of_dataframe = df.shape[0]

training_ds_rows = round(rows_of_dataframe * split_ratio)
test_ds_rows = round(rows_of_dataframe * (1- split_ratio))

df_training = df[:training_ds_rows]
df_test = df[training_ds_rows:]

## Normalize

In [18]:
training_set = tf.convert_to_tensor(df_training[['Volume','Open', 'Close']])
print(training_set.shape)

(588, 3)


In [19]:
plot_series_plotly(df_training['Date'], (training_set[:, 0],
                                         training_set[:, 1],
                                         training_set[:, 2]),
                   series_name=['Volume','Open', 'Close'], figure_title='Data Normalized')

In [20]:
minmax_scaler = MinMaxScaler(feature_range=(-1, 1))

training_set_normalized = minmax_scaler.fit_transform(training_set)

In [21]:
plot_series_plotly(df_training['Date'], (training_set_normalized[:, 0],
                                         training_set_normalized[:, 1],
                                         training_set_normalized[:, 2]),
                   series_name=['Volume','Open', 'Close'], figure_title='Data Normalized')

## Prepare features and labels

In [22]:
window_size = 20
batch_size = 32
shuffle_buffer_size = 1000
     
## CONSTANT
MU = 0.000001
NANO = 1e-9

In [23]:
# Generate the dataset windows
windowed_training_ds = windowed_dataset(training_set_normalized, window_size, 
                           batch_size, shuffle_buffer_size)

In [24]:
# Print properties of a single batch
for windows in windowed_training_ds.take(1):
  print(f'data type: {type(windows)}')
  print(f'number of elements in the tuple: {len(windows)}')
  print(f'shape of first element: {windows[0].shape}')
  print(f'shape of second element: {windows[1].shape}')
  print(f'shape of first element expanded: {tf.expand_dims(windows[0], axis=-1).shape}')

data type: <class 'tuple'>
number of elements in the tuple: 2
shape of first element: (32, 20, 3)
shape of second element: (32, 3)
shape of first element expanded: (32, 20, 3, 1)


## Build and compile the model

In [25]:
class TS_LSTM_Model(tf.keras.Model):
  def __init__(self, window_size,feature_size=1,
               normalizer_layer=None,
               denormalizer_layer=None,
               expand_dims_layer=True,
               **kwargs):
    super(TS_LSTM_Model, self).__init__(**kwargs)

    self.normalizer_1 = normalizer_layer
    self.denormalizer_1 = denormalizer_layer
    model_tune = tf.keras.models.Sequential()
    if(expand_dims_layer):
      model_tune.add(tf.keras.layers.Lambda(lambda x: tf.expand_dims(x, axis=-1),
                      input_shape=[window_size]))      
    model_tune.add(tf.keras.layers.Bidirectional(
        tf.keras.layers.LSTM(32, return_sequences=True)))
    model_tune.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32)))
    model_tune.add(tf.keras.layers.Dense(feature_size))
    self.seq_1 = model_tune

  def normalize(self, x):
    return self.normalizer_1(x)
  
  def denormalize(self, x):
    return self.denormalizer_1(x)

  @tf.function(reduce_retracing=True)   
  def call(self, x):
    x = self.seq_1(x)
    return x

## create model

In [26]:
learning_rate_value_all = 1e-6
epoch_value = 100

Since we are using minmaxscaler we already reshape the input dimension into `(Batch_size, window_size, feature_size)` so we do not need to add lambda expand dimension layer, so we set `expand_dims_layer=False` to the parameter of model

and input shape for `build()` would be
input_shape = (1, window_size, feature_size)

In [27]:
# Reset states generated by Keras
tf.keras.backend.clear_session()

model_tune2 = TS_LSTM_Model(window_size=window_size, 
                              normalizer_layer=None,
                              feature_size=training_set_normalized.shape[1],
                              denormalizer_layer=None,
                            expand_dims_layer=False)
# set built parameter

print(training_set.shape)
model_tune2.build(input_shape = (1, window_size, training_set_normalized.shape[1]))
model_tune2.summary()
# Set the training parameters
model_tune2.compile(loss=tf.keras.losses.Huber(), 
                    optimizer=tf.keras.optimizers.SGD(
                        learning_rate=learning_rate_value_all,
                        momentum=0.9))

(588, 3)
Model: "ts_lstm__model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 sequential (Sequential)     (1, 3)                    34243     
                                                                 
Total params: 34,243
Trainable params: 34,243
Non-trainable params: 0
_________________________________________________________________


## Tune the Learning Rate

As usual, you will pick a learning rate by running the tuning code below.

In [28]:
# Set the learning rate scheduler
lr_schedule = tf.keras.callbacks.LearningRateScheduler(
    lambda epoch: learning_rate_value_all * 10**(epoch / 20))

# Train the model
history_tune2 = model_tune2.fit(windowed_training_ds, epochs=epoch_value, 
                                callbacks=[lr_schedule],
                                verbose=0)

In [29]:
plot_loss_inlog_plotly(history_tune2, epoch_value, lrs_value=learning_rate_value_all)

## Train the Model

You can then proceed to train the model with your chosen learning rate. 

*Tip: When experimenting and you find yourself running different iterations of a model, you may want to use the [`clear_session()`](https://www.tensorflow.org/api_docs/python/tf/keras/backend/clear_session) method to declutter memory used by Keras. This is added in the first line below.*


In [30]:
# Reset states generated by Keras
tf.keras.backend.clear_session()

model_tune2 = TS_LSTM_Model(window_size=window_size, 
                              normalizer_layer=None,
                              denormalizer_layer=None,
                            feature_size=training_set_normalized.shape[1],
                            expand_dims_layer=False)
#model_tune2.load_weights('./checkpoints/my_checkpoint')

# set built parameter
print(training_set.shape)
model_tune2.build(input_shape = (1, window_size, training_set.shape[1]))
#model_tune2.summary()
# Set the training parameters
model_tune2.compile(loss=tf.keras.losses.Huber(), 
                    optimizer=tf.keras.optimizers.SGD(
                        learning_rate=0.028,
                        momentum=0.9))


# Train the model
history_build1 = model_tune2.fit(windowed_training_ds, epochs=epoch_value, 
                                verbose=0)

(588, 3)


In [31]:
plot_series_plotly(np.arange(0, epoch_value), history_build1.history['loss'],
                   figure_title='loss value',
                   xaxis_title='epoch', yaxis_title='Loss')

In [32]:
test_set_g2, results2 = plot_prediction_graph_plotly(
    model_tune2, df, training_ds_rows, 
    window_size, None, None,
    scaler=minmax_scaler,
    variable_names=['Volume', 'Open', 'Close'],
    series_name=['test set (close)',
                 'pred set (close)']
    )

dateset_to_forecast shape: (167, 3)
expanded dateset_to_forecast shape: (1, 20, 3)
forecast shape (147, 1, 3)
forecast squeezed shape (147, 3)


In [33]:
print(history_build1.history['loss'][-1])
print(tf.keras.metrics.mean_squared_error(test_set_g2[:,-1], results2[:,-1]).numpy())
print(tf.keras.metrics.mean_absolute_error(test_set_g2[:,-1], results2[:,-1]).numpy())

0.008724291808903217
7952.7695
68.490875


In [47]:
test_set_g2.shape

TensorShape([147, 3])

## tomorrow pred

In [34]:
test_set = tf.convert_to_tensor(df_test[['Volume', 'Open','Close']])

In [35]:
test_set[-1].numpy()

array([4.79215e+07, 4.34000e+03, 4.32000e+03])

In [36]:
with np.printoptions(precision=0, suppress=True):
    print(test_set[-1].numpy())

[47921500.     4340.     4320.]


In [37]:
test_set_normalized = minmax_scaler.transform(test_set)
test_set_normalized[-1]

array([-0.92540128,  0.55263158,  0.59276018])

In [38]:
tomorro_pred = minmax_scaler.inverse_transform(model_tune2.predict(
    np.expand_dims(test_set_normalized[-window_size:], axis=0)))

1/1 [==============================] - 0s 17ms/step


In [46]:
with np.printoptions(precision=13, suppress=True):
    print(tomorro_pred)

#for elem in tomorro_pred[0]:
#  print('{:.1f}'.format(elem))

[[1.0691342e+08 4.2976011e+03 4.2993813e+03]]


previous pred

In [52]:
with np.printoptions(precision=13, suppress=True):
  print((results2[-1,:].reshape(1, -1)))

[[1.1346653e+08 4.2751685e+03 4.2722119e+03]]


## save model

there are two method to save a model:
 - by calling `save()` function
 - by calling `save_weights()` function

In [ ]:
model_tune2.save('./model/lstm01')

In [ ]:
model_tune2.save_weights('./weights/lstm01')

## load model

### by calling `tf.keras.models.load_model`

In [ ]:
model_loaded0 = tf.keras.models.load_model('./model/lstm01')

In [ ]:
tomorrow_pred = minmax_scaler.inverse_transform(model_loaded0.predict(
    np.expand_dims(test_set_normalized[-window_size:], axis=0)))

1/1 [==============================] - 0s 18ms/step


In [ ]:
for elem in tomorro_pred[0]:
  print('{:.0f}'.format(elem))

81156152
3958
3972


### by loading weights

In [ ]:
model_loaded = TS_LSTM_Model(window_size=window_size, 
                              normalizer_layer=None,
                              denormalizer_layer=None,
                             feature_size=2,
                             expand_dims_layer=False
                             )

In [ ]:
model_loaded.load_weights('./weights/lstm01')

In [ ]:
tomorrow_pred = minmax_scaler.inverse_transform(model_loaded.predict(
    np.expand_dims(test_set_normalized[-window_size:], axis=0)))

1/1 [==============================] - 0s 19ms/step


In [ ]:
for elem in tomorrow_pred[0]:
  print('{:.0f}'.format(elem))

81156152
3958
3972
